FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN playwright install --with-deps firefox

COPY api ./api
COPY torrents ./torrents
COPY films ./films

WORKDIR /app/api

EXPOSE 8000

CMD ["uvicorn", "main_simple_graph:app", "--host", "0.0.0.0"]